### ISSUE TITLE
How this related to Facebook?

### ISSUE THREAD

**Issue by kodekrendel** [cgatian/webpack-image-placeholder#3]
Why you provide Demo link to Facebook site article? They use this package?

**Comment by cgatian** [comment]
This project is not affiliated in any way with Facebook.  They do not use this package.
The link provided is a blog post explaining how the underlying technique works.

**Comment by kodekrendel** [comment]
Then how is that "Demo"?

**Comment by cgatian** [comment]
Sorry the demo is the actual demo. The link is just explaining how the
technique works.
